$env:VITE_USE_FIREBASE_EMULATOR = 'true'
$env:VITE_AUTH_EMULATOR_URL = 'http://127.0.0.1:9099'
$env:VITE_FIRESTORE_EMULATOR_HOST = '127.0.0.1'
$env:VITE_FIRESTORE_EMULATOR_PORT = '8080'

npm.cmd run dev
